server:
  servlet:
    context-path: /campestre-sem-fila/api/v1
spring:
  h2:
    console:
      enabled: true
    datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: sa
      password: password
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/${NAME_DATABASE}
#    username: ${CAMPESTRE_SEM_FILA_USERNAME_DB}
#    password: ${CAMPESTRE_SEM_FILA_PASSWORD_DB}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true

backend:
  api-nota-fiscal:
    uri: http://localhost:8080/api/nota-nao-fiscal
